---
# Tâche pour transférer les données vers le serveur de dépôt externe

- name: (transfer_to_repository) Validate repository server configuration
  ansible.builtin.assert:
    that:
      - repository_server | length > 0
      - repository_path | length > 0
    fail_msg: "Configuration du serveur de dépôt incomplète. Veuillez définir repository_server et repository_path."
    success_msg: "Configuration du serveur de dépôt validée"
  run_once: true
  delegate_to: localhost
  tags:
    - transfer

# SFTP Transfer
- name: (transfer_to_repository) Transfer Excel report via SFTP
  ansible.builtin.copy:
    src: "{{ temp_excel_file }}"
    dest: "{{ repository_path }}/{{ report_filename }}"
    mode: '0644'
  delegate_to: "{{ repository_server }}"
  run_once: true
  tags:
    - transfer
  register: sftp_result

- name: (transfer_to_repository) Cleanup temporary files
  ansible.builtin.file:
    path: "{{ temp_inventory_path }}"
    state: absent
  run_once: true
  delegate_to: localhost
  when: cleanup_temp_files | bool
  tags:
    - transfer
    - cleanup
    - always