---
# collecte_inventaire.yml
# Playbook pour collecter l'inventaire des switches Aruba AOS-CX

- name: Collect Aruba switches inventory
  hosts: switches_aruba
  gather_facts: false
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_become: false
    # ansible_user: admin
    # ansible_password: demander via --ask-pass ou définir via fichier vault
  
  roles:
    - role: inventory_collector
      # Les variables du rôle peuvent être surchargées ici si nécessaire