---
# collecte_inventaire.yml
# Playbook pour collecter l'inventaire des switches Aruba AOS-CX

- name: Collect Aruba switches inventory
  hosts: switches_aruba
  gather_facts: false
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_become: false
    # ansible_user: admin
    # ansible_password: demander via --ask-pass ou définir via fichier vault
    
    # Configuration du serveur de dépôt pour stockage permanent
    # Ces variables peuvent être surchargées via l'inventaire ou --extra-vars
    repository_server: "{{ repository_server | default('ansible_local') }}"
    repository_path: "{{ repository_path | default('/opt/aruba_reports/inventory') }}"
    repository_user: "{{ repository_user | default('deploy') }}"
    # repository_password: défini via vault ou variables d'inventaire
  
  roles:
    - role: inventory_collector
      # Les variables du rôle peuvent être surchargées ici si nécessaire