---
# debug_tags.yml - Playbook pour débugger les tags

- name: Test des tags avec le rôle simple_firmware_updater
  hosts: switches_aruba
  gather_facts: no
  
  vars:
    switch_model: "{{ switch_model }}"
    firmware_filename: "{{ firmware_filename }}"
    firmware_source_type: "local"
    local_firmware_path: "/firmware/{{ switch_model }}"
    backup_path: "/backups/network/aruba/config_backups"
    
  tasks:
    - name: "(DEBUG) Lister toutes les tâches du rôle"
      ansible.builtin.debug:
        msg: "Démarrage du debug des tags"
      tags:
        - always
        
    - name: "(DEBUG) Générer un timestamp"
      ansible.builtin.set_fact:
        global_timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
      delegate_to: localhost
      run_once: true
      delegate_facts: true
      tags:
        - always
    
    - name: "(DEBUG) Inclure directement backup_config.yml"
      include_tasks: roles/simple_firmware_updater/tasks/backup_config.yml
      tags:
        - backup
        
    - name: "(DEBUG) Afficher le résultat"
      ansible.builtin.debug:
        msg: |
          Backup exécuté ? {{ backup_result is defined }}
          Fichier créé ? {{ backup_stat is defined and backup_stat.stat.exists | default(false) }}
      tags:
        - always