---
# simple_repository_test.yml
# Test ultra-simple de connexion au serveur de dépôt

- name: Test simple de connexion au dépôt
  hosts: repository_servers
  gather_facts: false
  
  tasks:
    - name: Test de ping basique
      ansible.builtin.ping:
      
    - name: Lister le répertoire home
      ansible.builtin.command:
        cmd: ls -la ~/
      register: home_ls
      changed_when: false
      
    - name: Afficher le résultat
      ansible.builtin.debug:
        var: home_ls.stdout_lines
        
    - name: Afficher le répertoire de travail actuel
      ansible.builtin.command:
        cmd: pwd
      register: current_dir
      changed_when: false
      
    - name: Afficher le répertoire actuel
      ansible.builtin.debug:
        msg: "Répertoire actuel: {{ current_dir.stdout }}"
        
    - name: Test des permissions d'écriture
      ansible.builtin.command:
        cmd: touch /tmp/ansible_test_file
      register: touch_test
      changed_when: false
      failed_when: false
      
    - name: Résultat du test d'écriture
      ansible.builtin.debug:
        msg: "{{ 'Écriture OK' if touch_test.rc == 0 else 'Écriture échouée' }}"
        
    - name: Nettoyer le fichier de test
      ansible.builtin.file:
        path: /tmp/ansible_test_file
        state: absent
      when: touch_test.rc == 0