---
# test_backup_only.yml - Test uniquement la sauvegarde

- name: Test de sauvegarde uniquement
  hosts: switches_aruba
  gather_facts: no
  
  vars:
    repository_server: "{{ hostvars[inventory_hostname]['repository_server'] | default('10.20.3.11') }}"
    backup_path: "/backups/network/aruba/config_backups"
    remote_temp_dir: "/tmp/ansible_simple_firmware"
    backup_enabled: true
    dry_run: false
    force_backup_in_dryrun: false
    msg_backup_success: "Sauvegarde de configuration réussie"
    msg_dryrun_skip: "[DRY-RUN] Cette étape serait exécutée en mode normal"
    
  tasks:
    - name: "Générer un timestamp"
      ansible.builtin.set_fact:
        global_timestamp: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
      delegate_to: localhost
      run_once: true
      delegate_facts: true
    
    - name: "Définir le nom du fichier de sauvegarde"
      ansible.builtin.set_fact:
        backup_filename: "config_backup_{{ inventory_hostname }}_{{ hostvars['localhost']['global_timestamp'] }}_DIRECT.cfg"
    
    - name: "Créer le répertoire temporaire local"
      ansible.builtin.file:
        path: "{{ remote_temp_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: "Sauvegarder la configuration"
      arubanetworks.aoscx.aoscx_backup_config:
        config_name: "running-config"
        output_file: "{{ remote_temp_dir }}/{{ backup_filename }}"
      register: backup_result

    - name: "Afficher le résultat"
      ansible.builtin.debug:
        msg: |
          Backup réussi: {{ backup_result is succeeded }}
          Fichier: {{ backup_filename }}
          
    - name: "Vérifier la sauvegarde locale"
      ansible.builtin.stat:
        path: "{{ remote_temp_dir }}/{{ backup_filename }}"
      register: backup_stat
      delegate_to: localhost
      
    - name: "Afficher la taille du fichier"
      ansible.builtin.debug:
        msg: "Fichier de sauvegarde créé: {{ backup_stat.stat.size | default(0) }} bytes"
      when: backup_stat.stat.exists | default(false)