---
# mixed_connection_test.yml
# Playbook démontrant l'utilisation de différents types de connexion

- name: Test avec différents types de connexion
  hosts: switches_aruba
  gather_facts: false
  vars:
    # Connexion par défaut pour le playbook
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
    ansible_become: false
    
  tasks:
    - name: Test avec connexion par défaut (aoscx)
      arubanetworks.aoscx.aoscx_facts:
        gather_subset:
          - host_name
          - software_version
      register: facts_result
      
    - name: Afficher les informations collectées via aoscx
      debug:
        msg:
          - "Connexion utilisée: {{ ansible_connection }}"
          - "Hostname: {{ facts_result.ansible_facts.ansible_net_hostname | default('N/A') }}"
          - "Version: {{ facts_result.ansible_facts.ansible_net_software_version | default('N/A') }}"
    
    - name: Exécuter show running-config via network_cli
      arubanetworks.aoscx.aoscx_command:
        commands:
          - "show running-config"
      register: running_config_result
      vars:
        ansible_connection: network_cli
        ansible_network_os: arubanetworks.aoscx.aoscx
        
    - name: Afficher les résultats de la commande network_cli
      debug:
        msg:
          - "Connexion utilisée pour cette tâche: network_cli"
          - "Taille de la configuration: {{ running_config_result.stdout[0] | length }} caractères"
          - "Premières lignes:"
          - "{{ running_config_result.stdout[0].split('\n')[:5] }}"
    
    - name: Test avec connexion par défaut après surcharge
      arubanetworks.aoscx.aoscx_command:
        commands:
          - "show version"
      register: version_result
      
    - name: Vérifier que la connexion par défaut est restaurée
      debug:
        msg:
          - "Connexion utilisée: {{ ansible_connection }}"
          - "La surcharge network_cli n'affecte que la tâche spécifique"
          - "Version extraite: {{ version_result.stdout[0].split('\n')[0] }}"
    
    - name: Bloc avec surcharge de connexion
      block:
        - name: Première commande du bloc
          arubanetworks.aoscx.aoscx_command:
            commands:
              - "show system"
          register: system_result
          
        - name: Deuxième commande du bloc
          arubanetworks.aoscx.aoscx_command:
            commands:
              - "show interface mgmt"
          register: interface_result
          
        - name: Afficher les résultats du bloc
          debug:
            msg:
              - "Toutes les tâches du bloc utilisent: network_cli"
              - "System info récupéré: {{ system_result.stdout[0].split('\n')[0] }}"
              - "Interface mgmt info récupéré: {{ interface_result.stdout[0].split('\n')[0] }}"
      vars:
        ansible_connection: network_cli
        ansible_network_os: arubanetworks.aoscx.aoscx
        
  post_tasks:
    - name: Vérification finale
      debug:
        msg:
          - "✅ Test terminé avec succès"
          - "✅ Connexion par défaut du playbook: {{ ansible_connection }}"
          - "✅ Les surcharges de connexion fonctionnent correctement"
          - "ℹ️  Chaque tâche peut utiliser son propre type de connexion"