---
# test_repository_connection.yml
# Playbook de test simple pour vérifier la connexion au serveur de dépôt

- name: Test de connexion au serveur de dépôt
  hosts: repository_servers
  gather_facts: true
  vars:
    # Variables de test (à adapter selon votre configuration)
    test_user: "{{ ansible_user | default('deploy') }}"
    
  tasks:
    - name: Test de connectivité basique
      ansible.builtin.ping:
      register: ping_result
      
    - name: Afficher le résultat du ping
      ansible.builtin.debug:
        msg: 
          - "✓ Connexion réussie au serveur {{ inventory_hostname }}"
          - "✓ Utilisateur connecté: {{ test_user }}"
          - "✓ Ping successful: {{ ping_result.ping }}"
    
    - name: Collecter les informations système de base
      ansible.builtin.debug:
        msg:
          - "Nom d'hôte: {{ ansible_hostname | default('Unknown') }}"
          - "Distribution: {{ ansible_distribution | default('Unknown') }} {{ ansible_distribution_version | default('') }}"
          - "Architecture: {{ ansible_architecture | default('Unknown') }}"
          - "Utilisateur effectif: {{ ansible_user_id | default('Unknown') }}"
          - "Répertoire home: {{ ansible_env.HOME | default('Unknown') }}"
          
    - name: Vérifier le répertoire home de l'utilisateur
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}"
      register: home_stat
      
    - name: Afficher les informations du répertoire home
      ansible.builtin.debug:
        msg:
          - "Répertoire home: {{ ansible_env.HOME }}"
          - "Existe: {{ home_stat.stat.exists }}"
          - "Permissions: {{ home_stat.stat.mode | default('Unknown') }}"
          - "Propriétaire: {{ home_stat.stat.pw_name | default('Unknown') }}"
          
    - name: Lister le contenu du répertoire home
      ansible.builtin.command:
        cmd: ls -la {{ ansible_env.HOME }}
      register: home_listing
      changed_when: false
      
    - name: Afficher le contenu du répertoire home
      ansible.builtin.debug:
        msg: 
          - "=== CONTENU DU RÉPERTOIRE HOME ==="
          - "{{ home_listing.stdout_lines }}"
          
    - name: Test de création d'un fichier temporaire
      ansible.builtin.tempfile:
        state: file
        suffix: .ansible_test
      register: temp_file
      
    - name: Écrire dans le fichier temporaire
      ansible.builtin.copy:
        content: |
          Test de connexion Ansible
          Date: {{ ansible_date_time.iso8601 }}
          Utilisateur: {{ ansible_user_id }}
          Serveur: {{ inventory_hostname }}
        dest: "{{ temp_file.path }}"
        mode: '0644'
        
    - name: Vérifier le fichier temporaire créé
      ansible.builtin.stat:
        path: "{{ temp_file.path }}"
      register: temp_file_stat
      
    - name: Lire le contenu du fichier temporaire
      ansible.builtin.slurp:
        src: "{{ temp_file.path }}"
      register: temp_file_content
      
    - name: Afficher le contenu du fichier temporaire
      ansible.builtin.debug:
        msg: 
          - "=== CONTENU DU FICHIER TEST ==="
          - "{{ temp_file_content.content | b64decode }}"
          
    - name: Nettoyer le fichier temporaire
      ansible.builtin.file:
        path: "{{ temp_file.path }}"
        state: absent
        
    - name: Tester les permissions sudo (optionnel)
      ansible.builtin.command:
        cmd: whoami
      register: whoami_result
      become: true
      failed_when: false
      
    - name: Afficher les informations sudo
      ansible.builtin.debug:
        msg:
          - "Utilisateur normal: {{ ansible_user_id }}"
          - "Utilisateur avec sudo: {{ whoami_result.stdout | default('Échec sudo') }}"
          - "Sudo disponible: {{ whoami_result.rc == 0 }}"
      when: whoami_result is defined
      
    - name: Tester la création d'un répertoire dans un chemin spécifique
      block:
        - name: Créer un répertoire de test
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/ansible_test_dir"
            state: directory
            mode: '0755'
          register: test_dir_creation
          
        - name: Créer un sous-répertoire
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/ansible_test_dir/subdir"
            state: directory
            mode: '0755'
            
        - name: Lister le répertoire de test
          ansible.builtin.command:
            cmd: ls -la {{ ansible_env.HOME }}/ansible_test_dir
          register: test_dir_listing
          changed_when: false
          
        - name: Afficher le contenu du répertoire de test
          ansible.builtin.debug:
            msg: 
              - "=== RÉPERTOIRE DE TEST CRÉÉ ==="
              - "{{ test_dir_listing.stdout_lines }}"
              
        - name: Nettoyer le répertoire de test
          ansible.builtin.file:
            path: "{{ ansible_env.HOME }}/ansible_test_dir"
            state: absent
            
      rescue:
        - name: Gestion d'erreur pour le test de répertoire
          ansible.builtin.debug:
            msg: "⚠️  Impossible de créer le répertoire de test: {{ ansible_failed_result.msg }}"
            
  post_tasks:
    - name: Résumé du test de connexion
      ansible.builtin.debug:
        msg:
          - "================================"
          - "✅ TEST DE CONNEXION TERMINÉ"
          - "================================"
          - "Serveur: {{ inventory_hostname }}"
          - "Utilisateur: {{ ansible_user_id }}"
          - "Home: {{ ansible_env.HOME }}"
          - "Sudo: {{ whoami_result.rc == 0 if whoami_result is defined else 'Non testé' }}"
          - "Écriture fichiers: ✅"
          - "Création répertoires: ✅"
          - "================================"
          - "🎉 Connexion au serveur de dépôt fonctionnelle"
          - "================================"