---
# Variables pour le rôle inventory_collector

# Structure des colonnes du fichier Excel (mise à jour avec platform)
colonnes_excel:
  - nom: "Nom du Switch"
    cle: "nom_switch"
    largeur: 20
  - nom: "Modèle"
    cle: "modele"
    largeur: 15
  - nom: "Plateforme"
    cle: "platform"
    largeur: 15
  - nom: "Numéro de Série"
    cle: "serial"
    largeur: 20
  - nom: "Version OS"
    cle: "version_os"
    largeur: 15
  - nom: "Date de Collecte"
    cle: "date_collecte"
    largeur: 15
  - nom: "Adresse IP"
    cle: "adresse_ip"
    largeur: 15

# Configuration CORRIGÉE pour le module aoscx_facts
facts_gather_subset:
  - product_info      # Pour obtenir le modèle et numéro de série (remplace hardware)
  - host_name         # Pour obtenir le nom d'hôte
  - platform_name     # Pour obtenir la plateforme
  - software_version  # Pour obtenir la version OS (remplace version)

# Mapping des clés Ansible facts vers nos variables
# ATTENTION : Les clés exactes peuvent varier selon la version du module
facts_mapping:
  hostname: "ansible_net_hostname"
  model: "ansible_net_model"
  serial: "ansible_net_serialnum"
  version: "ansible_net_version"
  platform: "ansible_net_system"

# Configuration de fallback si aoscx_facts échoue
# (conservé pour compatibilité descendante)
commandes_aoscx:
  nom_switch: "show hostname"
  modele: "show system | include 'Base Model'"
  serial: "show system | include 'Serial Number'"
  version_os: "show version"
  platform: "show system | include 'Platform'"

# Mappages des regex pour extraire les informations (fallback)
regex_extraction:
  nom_switch: "^Hostname\\s*:\\s*(.+)$"
  modele: "Base Model\\s*:\\s*(.+)$"
  serial: "Serial Number\\s*:\\s*(.+)$"
  version_os: "^Version\\s*:\\s*(.+)$"
  platform: "Platform\\s*:\\s*(.+)$"